# Generated by Django 4.2.5 on 2023-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_number', models.PositiveIntegerField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvv', models.PositiveIntegerField(max_length=3)),
                ('pix_key', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
