# Generated by Django 4.2.5 on 2023-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_alter_order_card_number_alter_order_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.CharField(max_length=8),
        ),
    ]
